log_level: debug
layout:
  readme: ./README-test.md
  book_index: ./book-index-test.md
  learning_paths: ./paths
  book_covers: ./assets/covers
badges:
  - category: &difficulty difficulty
    icons:
    - name: &beginner beginner
      code: ant
      desc: "Petty ant"
    - name: &easy easy
      code: hatched_chick
      desc: "Naive chicken"
    - name: &intermediate intermediate
      code: dog2
      desc: "Brave Dog"
    - name: &hard hard
      code: tiger2
      desc: "Fierce tiger"
    - name: &expert expert
      code: dragon
      desc: "Mighty dragon"
  - category: &progress progress
    icons:
    - name: &read read
      code: green_book
    - name: &scheduled scheduled
      code: blue_book
    - name: &scheduled not_scheduled
      code: orange_book
  - category: &rating rating
    icons:
    - name: &nice nice
      code: ok
    - name: &good good
      code: up
    - name: &very_good very_good
      code: cool
    - name: &excellent excellent
      code: top
  - category: &misc misc
    icons:
    - name: &must-read must_read
      code: bookmark
    - name: &old old
      code: arrows_counterclockwise
    - name: &new new
      code: new
    - name: &coming-soon coming-soon
      code: soon
    - name: &in-progress in-progress
      code: construction
learning_paths:
  - name: "APIs"
    ref: &apis apis
    status: *new
    desc: |
      Test
  - name: "System Design"
    ref: &system-design system-design
    status: *coming-soon
    desc: |
      You want to create systems that resolve complicated technical problems, to find optimal solutions, to learn how evolve your systems to the next level, to rack your brains designing wonderful architectures that withstand the overwhelming onslaught of hyped user hordes. Well, as AC/CD sing: It's a long way to the top if you wanna Rock' n' Roll. But do not yield, tough efforts often bring solid results, keep calm and read hard!
    related_paths:
      - *apis
  - name: "Microservices"
    ref: &microservices microservices
    status: *in-progress
    desc: |
      Test
books:
  - cover: building-microservices.jpeg
    title: Building Microservices
    subtitle: Designing Fine-Grained Systems
    order: 1
    draft: false
    url: https://learning.oreilly.com/library/view/-/9781492034018/
    authors:
      - Sam Newman
    release: 2022
    pages: 616
    desc: |-
      One of the most important books in the field. Far from advocating for the monolithic architectures exile, the book offers useful insights to help you identify use cases for monoliths, or when to turn to microservices. It will teach you what microservices really are, their evolutionary origin, principles, characteristics and all the new challenges they bring to the table. Finally, the author explains how organizations should evolve to adapt their internal structure and vision in order to efficiently deliver value using microservices architectures.
    learning_paths:
      - *system-design
      - *microservices
    badges:
      - category: *difficulty
        value: *intermediate
      - category: *progress
        value: *read
      - category: *rating
        value: *excellent
      - category: *misc
        value: *must-read
