sources:
  books_covers: ./assets/books/covers
  books_data: ./assets/books/data
  learning_paths_data: ./assets/paths/data
content:
  readme: ./README.md
  book_index: ./content/book-index.md
  learning_paths: ./content/paths
badges:
  - category: &difficulty difficulty
    icons:
    - name: &beginner beginner
      code: ant
      desc: "Petty ant"
    - name: &easy easy
      code: hatched_chick
      desc: "Naive chicken"
    - name: &intermediate intermediate
      code: dog2
      desc: "Brave Dog"
    - name: &hard hard
      code: tiger2
      desc: "Fierce tiger"
    - name: &expert expert
      code: dragon
      desc: "Mighty dragon"
  - category: &progress progress
    icons:
    - name: &read read
      code: green_book
    - name: &scheduled scheduled
      code: blue_book
    - name: &scheduled not_scheduled
      code: orange_book
  - category: &rating rating
    icons:
    - name: &nice nice
      code: ok
    - name: &good good
      code: up
    - name: &very_good very_good
      code: cool
    - name: &excellent excellent
      code: top
  - category: &misc misc
    icons:
    - name: &must-read must_read
      code: bookmark
    - name: &old old
      code: arrows_counterclockwise
  - category: &status status
    icons:
    - name: &stable stable
      code: stable
    - name: &new new
      code: new
    - name: &coming-soon coming-soon
      code: soon
    - name: &in-progress in-progress
      code: construction
