sources:
  books_covers: ./assets/books/covers
  books_data: ./assets/books/data
  learning_paths_data: ./assets/learning-paths/data
  badges_data: ./assets/badges/data
content:
  github:
    index: ./README.md
    book_index: ./content/book-index.md
    author_index: ./content/author-index.md
    learning_paths: ./content/learning-paths
  mkdocs:
    index: ./mkdocs/docs/index.md
    learning_paths: ./mkdocs/docs/learning-paths
    book_index: ./mkdocs/docs/references/book-index.md
    author_index: ./mkdocs/docs/references/author-index.md
    badges: ./mkdocs/docs/more/badges.md
    about: ./mkdocs/docs/more/about.md
    mentions: ./mkdocs/docs/more/mentions.md
