site_url: https://itreadventure.madravings.wtf
sources:
  books_covers: ./assets/books/covers
  books_data: ./assets/books/data
  learning_paths_data: ./assets/learning-paths/data
  learning_paths_tabs: ./assets/learning-paths/tabs
  badges_data: ./assets/badges/data
  tags_data: ./assets/tags/data
content:
  github:
    index: ./README.md
    book_index: ./content/book-index.md
    author_index: ./content/author-index.md
    tag_index: ./content/tag-index.md
    learning_paths: ./content/learning-paths
  mkdocs:
    index: ./mkdocs/docs/index.md
    learning_paths: ./mkdocs/docs/learning-paths
    book_index: ./mkdocs/docs/references/book-index.md
    author_index: ./mkdocs/docs/references/author-index.md
    tag_index: ./mkdocs/docs/references/tag-index.md
    badges: ./mkdocs/docs/badges.md
    about: ./mkdocs/docs/more/about.md
    books_read: ./mkdocs/docs/more/books-read.md
    mentions: ./mkdocs/docs/more/mentions.md
