name: Publish site via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Prepare assets
        run: |
          mkdir -p "${GITHUB_WORKSPACE}/mkdocs/docs/assets/books/covers"
          cp -r ./assets/books/covers "${GITHUB_WORKSPACE}/mkdocs/docs/assets/book/covers"
          mkdir -p "${GITHUB_WORKSPACE}/mkdocs/docs/assets/learning-path/icons"
          cp -r ./assets/learning-paths/icons "${GITHUB_WORKSPACE}/mkdocs/docs/assets/learning-path/icons"

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs/mkdocs.yml
          EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: enribd.github.io
          CUSTOM_DOMAIN: itreadventure.madravings.wtf
          GITHUB_REPOSITORY: enribd/choose-your-own-it-readventure
          REQUIREMENTS: mkdocs/requirements.txt
