name: Publish site via GitHub Pages
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main
        uses: actions/checkout@v2

      - name: Prepare assets
        run: |
          mkdir -p ./mkdocs/docs/assets/books
          cp -r ./assets/books/covers ./mkdocs/docs/assets/books
          mkdir -p ./mkdocs/docs/assets/learning-paths
          cp -r ./assets/learning-paths/icons ./mkdocs/docs/assets/learning-paths
          cp ./assets/favicon.png ./mkdocs/docs/assets/favicon.png

      - name: Set custom domain
        env:
          CUSTOM_DOMAIN: itreadventure.madravings.wtf
        run: echo "${CUSTOM_DOMAIN}" > ./mkdocs/docs/CNAME

      - name: Deploy docs
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CONFIG_FILE: mkdocs/mkdocs.yml
          EXTRA_PACKAGES: build-base
          # GITHUB_DOMAIN: enribd.github.io
          CUSTOM_DOMAIN: itreadventure.madravings.wtf
          GITHUB_REPOSITORY: enribd/choose-your-own-it-readventure
          REQUIREMENTS: mkdocs/requirements.txt
