# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json
site_name: "Choose your own IT readventure!"
site_author: enribd
dev_addr: "127.0.0.1:8000"
site_url: https://itreadventure.madravings.wtf
repo_url: https://github.com/enribd/choose-your-own-it-readventure
# nav: setup with awesome-pages plugin
theme:
  name: material
  favicon: assets/favicon.png
  logo: assets/logo.png
  icon:
    repo: fontawesome/brands/github
  font:
    text: Montserrat
    # text: Source Sans Pro
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: orange
      accent: deep orange
      scheme: default
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: orange
      accent: deep orange
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
extra:
  analytics:
    provider: google
    property: G-R2CDSTQBVL
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/enribd/choose-your-own-it-readventure
      name: github
    - icon: fontawesome/brands/golang 
      name: golang
    - icon: fontawesome/brands/docker 
      name: docker
markdown_extensions:
  - def_list
  - tables
  - attr_list
  - abbr
  - md_in_html
  - smarty
  - admonition
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
extra_css:
  - stylesheets/extra.css
plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - glightbox
  - awesome-pages
